---
namespace: dev-k8sbot

image:
  tag: dev

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  annotations:
    kubernetes.io/ingress.class: kong-dev-k8sbot
    certmanager.k8s.io/cluster-issuer: kong-dev
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    configuration.konghq.com: slack-oauth-ingress-cert-manager
  host: slack-oauth.dev.managedkube.com
  tls:
  - secretName: slack-oauth-tls
    hosts:
    - slack-oauth.dev.managedkube.com
